[versions]
agp = "9.0.0"
kotlin = "2.3.0"
coreKtx = "1.17.0"

[libraries]
androidx-core = { group = "androidx.core", name = "core", version.ref = "coreKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
