language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base qt59declarative qt59multimedia qt59quickcontrols qt59quickcontrols2 qt59graphicaleffects libsdl1.2-dev libesd0-dev libsqlite3-dev libv4l-dev
  - source /opt/qt*/bin/qt*-env.sh

script:
  - cd bld/libuv
  - make -j$(nproc)
  - sudo cp libuv.a /usr/lib
  - mkdir -p ../../lib ; cp libuv.a ../../lib/libuv.a
  - sudo cp include/uv.h /usr/share/include
  - cd -
  - qmake CONFIG+=appdir CONFIG+=release PREFIX=/usr DWYCO_CONFDIR=phoobld phoobld.pro # FIXME; remove the need for a special "appdir" configuration
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir -j$(nproc) install
  - cd phoo/ # FIXME
  - find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - # ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage -verbose=2

after_success:
  - find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file Dwyco*.AppImage https://transfer.sh/Dwyco-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Dwyco*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
