struct fn_rules  {const char *name; char **pfx; int cacheable; DwString *cached_val;};
%%
xferdl, &System_prefix, 1
servers2, &User_prefix, 1
entropy, &User_prefix, 1
system.dh, &System_prefix, 1
dwyco.dh, &System_prefix, 1
poli, &System_prefix, 1
qtabs, &System_prefix, 1
auth, &User_prefix, 1
accept, &User_prefix, 1
always, &User_prefix, 1
pals, &User_prefix, 1
timing, &User_prefix, 1
noise, &User_prefix, 1
ignore, &User_prefix, 1
never, &User_prefix, 1
theygrnt, &User_prefix, 1
igrant, &User_prefix, 1
stats, &User_prefix, 1
crashed, &User_prefix, 1
lhcore, &User_prefix, 1
crumb, &User_prefix, 1
infos, &User_prefix, 1
sinfo, &User_prefix, 1
inprogress, &User_prefix, 1
trash, &User_prefix, 1
outbox, &User_prefix, 1
inbox, &User_prefix, 1
prf, &User_prefix, 1
prf2, &User_prefix, 1
pk, &User_prefix, 1
xfer, &User_prefix, 1
.dbg, &User_prefix, 0
.usr, &User_prefix, 0
.dif, &User_prefix, 0
.aux, &User_prefix, 0
.log, &Tmp_prefix, 0
.out, &Tmp_prefix, 0
.q, &User_prefix, 0
.enc, &User_prefix, 0
.jpg, &Tmp_prefix, 0
.tmp, &Tmp_prefix, 0
.ppm, &Tmp_prefix, 0
.exe, &System_prefix, 0
.dyc, &User_prefix, 0
.fle, &User_prefix, 0
.idx, &User_prefix, 0
.pub, &User_prefix, 0
.prv, &User_prefix, 0
.sql, &User_prefix, 0
.pat, &System_prefix, 0
.urd, &User_prefix, 0
.tdb, &Tmp_prefix, 0
