language: cpp
compiler: gcc
os:
  - linux
  - osx
osx_image: xcode9.2
dist: trusty
sudo: require

before_install:
 - ./deps.sh

script:
 - ./ci.sh

after_success:
 - # wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
 - # bash upload.sh CDC-X

branches:
  except:
  - master
