
/* ===
; Copyright (c) 1995-present, Dwyco, Inc.
;
; This Source Code Form is subject to the terms of the Mozilla Public
; License, v. 2.0. If a copy of the MPL was not distributed with this file,
; You can obtain one at https://mozilla.org/MPL/2.0/.
*/
#include "pfx.h"
#include "dlli.h"


QByteArray User_pfx;
QByteArray Sys_pfx;
QByteArray Tmp_pfx;

QByteArray User_pfx_native;
QByteArray Sys_pfx_native;
QByteArray Tmp_pfx_native;

QByteArray
add_pfx(const QByteArray& pfx, const QByteArray& fn)
{
    QByteArray ret = pfx;
    ret += "/";
    ret += fn;
    return ret;
}

QByteArray
random_fn()
{
    char *r;
    dwyco_random_string2(&r, 10);
    QByteArray f(r, 10);
    dwyco_free_array(r);

    return f.toHex();
}

// note: this is a hack, we don't generate html stuff, but
// old messages generated by icuii might have html in them
QByteArray
get_extended(QByteArray txt)
{
    int i = txt.indexOf("<html>", 0);
    if(i == -1)
        return txt;
    txt.remove(0, i);
    // get rid of head too, old msgs have a lot of this in them
    i = txt.indexOf("</head>", 0);
    if(i == -1)
        return txt;
    txt.remove(0, i + 7);
    txt.prepend("<html>");
    return txt;
}
