######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 21 07:50:33 2018
######################################################################

TEMPLATE = app
CONFIG -= qt
TARGET = tqmap
DEPENDPATH += .
INCLUDEPATH += ..
QMAKE_CXXFLAGS += -std=c++11 --coverage
QMAKE_LFLAGS += -std=c++11 --coverage

# Input
SOURCES += tqmap.cpp 
