set(DWYCO_APP "dwycobg")
set(DWYCOBG 1)
add_compile_definitions(VCCFG_FILE)
add_compile_definitions($<$<CONFIG:Debug>:DWYCO_DEBUG>)
set(VCCFG_COMP ${CMAKE_CURRENT_SOURCE_DIR}/../../${DWYCO_CONFDIR})
add_compile_definitions(DWYCO_VC_CONV)

if(NOT WIN32)
set(CMAKE_CXX_COMPILER_LAUNCHER ccache)
endif()

if(UNIX AND NOT APPLE)
    add_compile_definitions(UNIX LINUX)
    add_compile_options(-Wall -Wno-unused-parameter -Wno-reorder -Wno-unused-variable -Wno-unused-function)
endif()
if(WIN32)
add_compile_definitions(_WIN32 __WIN32__ _Windows)
add_compile_options(/wd4100 /wd4068 /wd4189 /wd4291)
endif()
if(APPLE)
    add_compile_definitions(MACOSX LINUX UNIX)
    add_compile_options(-Wall -Wno-unused-parameter -Wno-reorder -Wno-unused-variable -Wno-unused-function)
endif()
