/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dwyco.phoo;

public class dwybg {
  public static int dwyco_background_processing(int port, int exit_if_outq_empty, String sys_pfx, String user_pfx, String tmp_pfx, String token) {
    return dwybgJNI.dwyco_background_processing(port, exit_if_outq_empty, sys_pfx, user_pfx, tmp_pfx, token);
  }

  public static void dwyco_set_aux_string(String str) {
    dwybgJNI.dwyco_set_aux_string(str);
  }

  public static void dwyco_clear_contact_list() {
    dwybgJNI.dwyco_clear_contact_list();
  }

  public static int dwyco_add_contact(String name, String phone, String email) {
    return dwybgJNI.dwyco_add_contact(name, phone, email);
  }

  public static void dwyco_signal_msg_cond() {
    dwybgJNI.dwyco_signal_msg_cond();
  }

  public static void dwyco_wait_msg_cond(int ms) {
    dwybgJNI.dwyco_wait_msg_cond(ms);
  }

  public static void dwyco_write_token(String token) {
    dwybgJNI.dwyco_write_token(token);
  }

}
